language: cpp
# command to install dependencies
sudo: enabled
dist: trusty
group: travis_lts
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libc++-dev
            - libgtest-dev
            - make
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libgtest-dev
            - make
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libgtest-dev
            - make
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libgtest-dev
            - make
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - export CWD=$PWD
  - cd /usr/src/gtest
  - if [[ $CXX == *"g++"* ]]; then
      sudo cmake CMakeLists.txt;
    else
      sudo cmake CMakeLists.txt -DCMAKE_CXX_FLAGS="$CXX_FLAGS -stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-lc++abi";
    fi
  - sudo make
  - sudo cp *.* /usr/lib/
  - cd $CWD
script:
  - bash ./build_linux.sh