language: cpp
# command to install dependencies
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os: linux
addons:
  apt:
    packages:
      - libgtest-dev
      - libboost-all-dev
      - make
      - cmake
install:
  - export CWD=$PWD
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt;
  - sudo make
  - sudo cp *.* /usr/lib/
  - cd $CWD
script:
  - bash ./build_linux.sh
