language: cpp
# command to install dependencies
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os: linux
addons:
  apt:
    packages:
      - libgtest-dev
      - libboost-all-dev
      - make
      - cmake
install:
  - export CWD=$PWD
  - mkdir gtest
  - cp -r /usr/src/gtest/* gtest/
  - cd gtest
  - cmake CMakeLists.txt;
  - make
  - sudo cp *.* /usr/lib/
  - cd $CWD
script:
  - bash ./build_linux.sh
