language: cpp
# command to install dependencies
sudo: enabled
dist: bionic
group: travis_lts
matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - clang
            - build-essential
            - libstdc++-devel
            - libc++-dev
            - libgtest-dev
            - libboost-all-dev
            - make
            - cmake
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      addons:
        apt:
          packages:
            - g++
            - build-essential
            - libgtest-dev
            - libboost-all-dev
            - make
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - export CWD=$PWD
  - cd /usr/src/gtest
  - if [[ "$CXX" == *"clang++"* ]]; then
      echo "using clang++";
      sudo cmake CMakeLists.txt -DCMAKE_CXX_FLAGS="$CXX_FLAGS -stdlib=libc++ -DGTEST_USE_OWN_TR1_TUPLE=1";
    else
      echo "using g++";
      sudo cmake CMakeLists.txt;
    fi
  - sudo make
  - sudo cp *.* /usr/lib/
  - cd $CWD
script:
  - bash ./build_linux.sh
