language: cpp
# command to install dependencies
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os: linux
addons:
  apt:
    packages:
      - libgtest-dev
      - libboost-all-dev
      - make
      - cmake
install:
  - export CWD=$PWD
  - cd /usr/src/gtest
  - if [[ "$CXX" == *"clang++"* ]]; then
      echo "using clang++";
      sudo cmake CMakeLists.txt -DCMAKE_CXX_FLAGS="$CXX_FLAGS -stdlib=libc++ -DGTEST_USE_OWN_TR1_TUPLE=1";
    else
      echo "using g++";
      sudo cmake CMakeLists.txt;
    fi
  - sudo make
  - sudo cp *.* /usr/lib/
  - cd $CWD
script:
  - bash ./build_linux.sh
