language: cpp
# command to install dependencies
sudo: enabled
dist: trusty
group: travis_lts
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libgtest-dev
      - make
      - cmake
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - export CWD=$PWD
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd $CWD
script:
  - bash ./build_linux.sh