name: CMake Linux build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt install -y g++-9 libboost-all-dev libgtest-dev libc++-dev make cmake
      - name: Prepare
        env:
          CXXFLAGS: -O2
          CC: gcc-9
          CXX: g++-9
        run: |
          sudo ln -sf /usr/bin/gcov-9 /usr/bin/gcov
          sudo ln -sf /usr/bin/gcov-9 /usr/bin/gcov
          wget http://mirrors.edge.kernel.org/ubuntu//pool/universe/l/lcov/lcov_1.14-2_all.deb
          sudo dpkg -i lcov_1.14-2_all.deb || sudo apt-get install -f -y
          sudo gem install coveralls-lcov
          export CWD=$PWD
          mkdir gtest
          cp -r /usr/src/gtest/* gtest/
          cd gtest
          cmake CMakeLists.txt
          make
          sudo cp *.* /usr/lib/
          cd $CWD
      - name: Compile
        env:
          CXXFLAGS: -O2
          CC: gcc-9
          CXX: g++-9
        run: |
          bash -e ./build_linux.sh
      - name: Coverage
        run: |
          echo "starting generate coverage report";
          lcov --directory ./build/ --capture --output-file --rc lcov_branch_coverage=1 ./coverage.info
          lcov --remove ./coverage.info '/usr/*' '*/tests/*' --output-file ./coverage.info
          lcov --list ./coverage.info
          coveralls-lcov ./coverage.info